@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}
@childId = 63c85b3df6d6c1e816c106a1

###

GET {{host}}/api/children HTTP/1.1
Accept: application/json

###
GET {{host}}/api/children/{{childId}} HTTP/1.1
Accept: application/json